version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rawler"
    labels:
      - "improvement"
    assignees:
      - "cytrinox"
    schedule:
      interval: "daily"
 - package-ecosystem: "cargo"
    directory: "/bin/dnglab"
    labels:
      - "improvement"
    assignees:
      - "cytrinox"
    schedule:
      interval: "daily"
