version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rawler"
    labels:
      - "improvement"
    assignees:
      - "cytrinox"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bin/dnglab"
    labels:
      - "dependency"
    assignees:
      - "cytrinox"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/embedftp"
    labels:
      - "dependency"
    assignees:
      - "cytrinox"
    schedule:
      interval: "daily"

