language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    recipients:
      - pedro@pedrocr.net
    on_success: never
    on_failure: always
  irc: "irc.mozilla.org#chimper"
