[package]
name = "rawloader"
version = "0.2.0"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]
description = "A library to extract the data from camera raw formats"
#documentation = "..."
#homepage = "..."
repository = "https://github.com/pedrocr/rawloader"
license = "LGPL-2.1"

build = "data/cameras/join.rs"

[dependencies]
itertools = "0.4.18"
toml = "0.2.0"
glob = "0.2.11"

[build-dependencies]
glob = "0.2.11"
