[package]
name = "rawloader"
version = "0.13.1"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]
description = "A library to extract the data from camera raw formats"
#documentation = "..."
#homepage = "..."
repository = "https://github.com/pedrocr/rawloader"
license = "LGPL-2.1"

build = "data/cameras/join.rs"

[dependencies]
toml = "0.2.0"
time = "0.1.35"
enum_primitive = "0.1.0"
num = "0.1.35"
lazy_static = "0.2.1"
byteorder = "0.5.3"
rayon = "0.5.0"

[build-dependencies]
glob = "0.2.11"

[profile.release]
panic = "unwind"
#debug-assertions = true
