[package]
name = "rawloader"
version = "0.10.0"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]
description = "A library to extract the data from camera raw formats"
#documentation = "..."
#homepage = "..."
repository = "https://github.com/pedrocr/rawloader"
license = "LGPL-2.1"

build = "data/cameras/join.rs"

[dependencies]
itertools = "0.4.18"
toml = "0.2.0"
crossbeam = "0.2.10"
time = "0.1.35"
enum_primitive = "0.1.0"
num = "0.1.35"
num_cpus = "1.1.0"
lazy_static = "0.2.1"
byteorder = "0.5.3"

[build-dependencies]
glob = "0.2.11"

[profile.release]
panic = "unwind"
#debug-assertions = true
