[package]
authors = ["Daniel Vogelbacher <daniel@chaospixel.com>"]
edition = "2018"
name = "dnglab"
version = "0.1.0-rc3"
description = "Camera RAW to DNG file format converter"
license = "LGPL-2.1"
repository = "https://github.com/dnglab/dnglab"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = "2.33.3"
fern = {version = "0.5", features = ["colored"]}
log = "0.4"
prettytable-rs = "^0.8"
rawler = {path = "../../rawler"}
image = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1"
itertools = "0.9"
thiserror = "1.0.25"

[package.metadata.deb]
maintainer = "Daniel Vogelbacher <daniel@chaospixel.com>"
license-file = ["../../LICENSE", "0"]
extended-description = """\
Utility for converting digital camera RAW format files\
into Digital Negatives (DNG)."""
section = "graphics"
priority = "optional"
