[package]
name = "dnglab"
version = "0.1.0"
authors = ["Daniel Vogelbacher <daniel@chaospixel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = "2.33.3"
fern = { version = "0.5", features = ["colored"] }
log = "0.4"
prettytable-rs = "^0.8"
